# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2020

# Custom your favicon.ico in `site/source`
favicon: /favicon/favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  归档: /archives
  关于: /about
  订阅: /atom.xml

archive_generator:
  per_page: 0
  yearly: true
  monthly: false
  daily: false

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>testing...</p>
widget:
  Tags: true
  Categories: true
  Custom: false
  Friends: true

widget_custom:
    title: 关于博主
    content: <a href="https://github.com/grayguest"><img src="/svg/github.svg" style="width:23px; hegiht:23px" /></a> &nbsp;&nbsp;&nbsp; <a href="https://weibo.com/hansxx"><img src="/svg/weibo.svg" style="width:23px; hegiht:23px" /></a> &nbsp;&nbsp;&nbsp; <a href="https://www.zhihu.com/people/xiaopo"><img src="/svg/zhihu-circle-fill.svg" style="width:23px; hegiht:23px" /></a> &nbsp;&nbsp;&nbsp; <a href="https://space.bilibili.com/157700884"><img src="/svg/billbill.svg" style="width:23px; hegiht:23px" /></a>

friend_list:
  爱黑武: https://bbs.ihei5.com
  dustyposa: https://dustyposa.github.io

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false # gitment评论系统开关
  owner: grayguest # GitHub用户名
  repo: grayguest.github.io # 存储评论数据的GitHub仓库的仓库名
  client_id: 84cea9ea417cfc735881 # OAuth Application的Client ID
  client_secret: 392b68089a1739b052eb2aebfbc9512813961a6a # OAuth Application的Client Secret
  lazy: false # 评论懒加载开关

# Gitalk
# Introduction: https://github.com/gitalk/gitalk
gitalk:
  enable: true
  owner: grayguest # GitHub用户名
  repo: grayguest.github.io # 存储评论数据的GitHub仓库的仓库名
  client_id: 84cea9ea417cfc735881 # OAuth Application的Client ID
  client_secret: 392b68089a1739b052eb2aebfbc9512813961a6a # OAuth Application的Client Secret
  admin: ['grayguest']
  createIssueManually: true
  distractionFreeMode: false

# ===========================================
# Version
# ===========================================
version: 1.1
