menu:
  - title: 首页
    url:
    intro: ""
    icon: "fa fa-home"
  - title: 归档
    url: archives
    intro: ""
    icon: "fa fa-list"
  - title: 关于
    url: about
    intro: ""
    icon: "fa fa-info-circle"
  - title: RSS
    url: atom.xml
    intro: "这是一个订阅源"
    icon: "fa fa-rss"

links:
  - title: "GitHub"
    url: https://github.com/grayguest
    intro: "GrayGuest"
    icon: "fa fa-github"
  - title: "微博"
    url: https://weibo.com/hansxx
    intro: "寒沙胜雪"
    icon: "fa fa-weibo"
  - title: "知乎"
    url: https://www.zhihu.com/people/xiaopo
    intro: "小破"
    icon: "fa fa-zhihu"
  - title: "B站"
    url: https://space.bilibili.com/157700884
    intro: "寒沙胜雪"
    icon: "fa fa-billbill"

widgets:
- recent_posts
- category
- tag
- links

rss:
favicon: favicon.ico
google_analytics:
# baidu_analytics: 392796d51567e848aebf813b65cb8656
footer: ""
